// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserAuth(ctx context.Context, arg CreateUserAuthParams) (UserAuth, error)
	DeleteExpiredUserAuth(ctx context.Context) error
	DeleteOrganization(ctx context.Context, id int64) error
	DeleteTenant(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteUserAuth(ctx context.Context, id int64) error
	GetOrganization(ctx context.Context, id int64) (Organization, error)
	GetTenant(ctx context.Context, id int64) (Tenant, error)
	GetTenantBySubdomain(ctx context.Context, subdomain string) (Tenant, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserAuthByToken(ctx context.Context, refreshToken sql.NullString) (UserAuth, error)
	GetUserAuthByUserID(ctx context.Context, userID int64) (UserAuth, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error)
	ListTenantsByOrganization(ctx context.Context, arg ListTenantsByOrganizationParams) ([]Tenant, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserAuth(ctx context.Context, arg UpdateUserAuthParams) (UserAuth, error)
}

var _ Querier = (*Queries)(nil)
