// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddUserToTenant(ctx context.Context, arg AddUserToTenantParams) (TenantUser, error)
	CheckUserBelongsToTenant(ctx context.Context, arg CheckUserBelongsToTenantParams) (bool, error)
	CountOrganizations(ctx context.Context) (int64, error)
	CountTenantsByOrganization(ctx context.Context, organizationID uuid.UUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountUsersNotInTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteOrganization(ctx context.Context, id uuid.UUID) error
	DeleteTenant(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationByTenant(ctx context.Context, tenantID uuid.UUID) (Organization, error)
	GetOrganizationWithTenants(ctx context.Context, id uuid.UUID) (GetOrganizationWithTenantsRow, error)
	GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetTenantBySubdomain(ctx context.Context, subdomain string) (Tenant, error)
	GetTenantUser(ctx context.Context, arg GetTenantUserParams) (TenantUser, error)
	GetTenantWithUserCount(ctx context.Context, id uuid.UUID) (GetTenantWithUserCountRow, error)
	GetTenantsByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Tenant, error)
	GetTenantsByUser(ctx context.Context, userID uuid.UUID) ([]Tenant, error)
	GetTenantsByUserID(ctx context.Context, userID uuid.UUID) ([]GetTenantsByUserIDRow, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByCognitoID(ctx context.Context, cognitoID string) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserWithTenants(ctx context.Context, id uuid.UUID) (GetUserWithTenantsRow, error)
	GetUsersByTenant(ctx context.Context, tenantID uuid.UUID) ([]User, error)
	GetUsersNotInTenant(ctx context.Context, arg GetUsersNotInTenantParams) ([]User, error)
	ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error)
	ListTenantUsers(ctx context.Context, tenantID uuid.UUID) ([]ListTenantUsersRow, error)
	ListTenantsByOrganization(ctx context.Context, arg ListTenantsByOrganizationParams) ([]Tenant, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RemoveUserFromTenant(ctx context.Context, arg RemoveUserFromTenantParams) error
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserRoleInTenant(ctx context.Context, arg UpdateUserRoleInTenantParams) (TenantUser, error)
}

var _ Querier = (*Queries)(nil)
